name: CI Build (Dummy)

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'src/**'
      - 'gradle/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Bypass CI
      run: echo "No code changes detected. Bypassing build."
